# CI Pipeline description
# Checks out on a remote machine
# And then runs all dependency requirements
# In order to build and publish a pre-built artifact

trigger:
- main

pool:
  name: "ansible"

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'

- task: Npm@1
  inputs:
    command: 'install'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '*/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '680ed216-9463-467e-90b3-b1757cdb7c2c'
    vstsFeedPackagePublish: 'app-artifact'
    versionOption: 'patch'
    packagePublishDescription: 'publish to Azure Artifacts'